version: '3.7'

services:
  db:
    image: postgres:15
    container_name: postgres-mxrt
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=persona-user
      - POSTGRES_PASSWORD=persona-password
      - POSTGRES_DB=persona

  app:
    container_name: app
    image: persona:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    expose:
      - 8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

volumes:
  pgsql_data: